[tool.poetry]
name = "flaskproject"
version = "0.1.0"
description = ""
authors = ["Rizal M"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.0"
pydantic = "^2.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
